import{randomUUID}from"node:crypto";import{NextResponse}from"next/server";import{z}from"zod";import{createAdminClient,createServerNeonClient}from"@/lib/neon/server";
const Body=z.object({action:z.enum(["claim","succeed","fail","replay","authorize_trigger"]),lease_id:z.string().max(120).optional(),error:z.string().max(1000).optional(),task_authorization_id:z.string().uuid().optional(),tool_name:z.string().max(240).optional()}).strict();
export async function POST(req:Request,p:{params:Promise<{eventId:string}>}){const{eventId}=await p.params;const session=await createServerNeonClient();const{data:u}=await session.auth.getUser();if(!u.user)return NextResponse.json({error:"Authentication required."},{status:401});const parsed=Body.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid event transition."},{status:400});const b=parsed.data,admin=createAdminClient();const loaded=await admin.from("webhook_events").select("id,user_id,server_id,status,attempt_count,max_attempts,lease_id,correlation_id,event_type").eq("id",eventId).eq("user_id",u.user.id).maybeSingle();if(!loaded.data)return NextResponse.json({error:"Event not found."},{status:404});const event=loaded.data;let from=event.status,to=from,reason:string|null=null,leaseId=b.lease_id??`whlease_${randomUUID()}`;
 if(b.action==="claim"){const claim=await admin.rpc("claim_webhook_event",{p_event_id:event.id,p_user_id:u.user.id,p_lease_id:leaseId,p_lease_until:new Date(Date.now()+30_000).toISOString()});if(claim.error||claim.data!==true)return NextResponse.json({error:"Event is not ready or is leased.",claimed:false},{status:409});to="processing";}
 else if(b.action==="succeed"){if(from!=="processing"||event.lease_id!==b.lease_id)return NextResponse.json({error:"Matching processing lease required."},{status:409});to="succeeded";await admin.from("webhook_events").update({status:to,processed_at:new Date().toISOString(),lease_id:null,lease_until:null,last_error:null}).eq("id",event.id).eq("lease_id",b.lease_id);}
 else if(b.action==="fail"){if(from!=="processing"||event.lease_id!==b.lease_id)return NextResponse.json({error:"Matching processing lease required."},{status:409});const dead=event.attempt_count>=event.max_attempts;to=dead?"dead_letter":"retry_scheduled";reason=b.error??"Processing failed.";await admin.from("webhook_events").update({status:to,last_error:reason,lease_id:null,lease_until:null,...(dead?{dead_lettered_at:new Date().toISOString()}:{next_attempt_at:new Date(Date.now()+Math.min(300_000,1000*2**Math.max(0,event.attempt_count-1))).toISOString()})}).eq("id",event.id).eq("lease_id",b.lease_id);}
 else if(b.action==="replay"){if(!["dead_letter","succeeded","retry_scheduled"].includes(from))return NextResponse.json({error:"Only completed, scheduled, or dead-letter events can be replayed."},{status:409});to="received";reason="Owner-requested replay";await admin.from("webhook_events").update({status:to,attempt_count:0,next_attempt_at:null,lease_id:null,lease_until:null,last_error:null,dead_lettered_at:null,processed_at:null}).eq("id",event.id).eq("user_id",u.user.id);}
 else{if(!b.task_authorization_id||!b.tool_name)return NextResponse.json({error:"task_authorization_id and tool_name required."},{status:400});const task=await admin.from("task_authorizations").select("id,purpose,allowed_tools,expires_at,revoked_at").eq("id",b.task_authorization_id).eq("user_id",u.user.id).eq("server_id",event.server_id).is("revoked_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();if(!task.data||!(task.data.allowed_tools as string[]).includes(b.tool_name))return NextResponse.json({error:"Task authorization does not permit this webhook trigger."},{status:403});to=from;reason=`Authorized ${b.tool_name}`;await admin.from("webhook_events").update({task_authorization_id:task.data.id,trigger_tool:b.tool_name}).eq("id",event.id).eq("user_id",u.user.id);await admin.from("tool_call_logs").insert({server_id:event.server_id,user_id:u.user.id,tool_name:b.tool_name,status:"authorized",method:"WEBHOOK",path:event.event_type??"event",execution_mode:"webhook_trigger_authorization",trace_id:event.correlation_id,attempt_count:0,task_authorization_id:task.data.id,purpose:task.data.purpose,summary:`Webhook event ${event.id} authorized trigger ${b.tool_name}; execution remains subject to normal runtime policy and audit.`});}
 await admin.from("webhook_event_transitions").insert({event_id:event.id,user_id:u.user.id,from_status:from,to_status:to,reason,correlation_id:event.correlation_id});return NextResponse.json({event_id:event.id,from_status:from,status:to,lease_id:b.action==="claim"?leaseId:null,correlation_id:event.correlation_id});}
