blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/codewithriza/astrail/security/advisories/new
    about: Report sensitive vulnerabilities privately.
