-- P2 safe reconciliation, mapping versions/templates, overlays and benchmarks.
alter table if exists public.mcp_servers add column if not exists openapi_overlay jsonb;
alter table if exists public.mcp_servers add column if not exists curated_operation_ids jsonb not null default '[]'::jsonb;
alter table if exists public.tool_schema_versions add column if not exists field_mappings jsonb;
alter table if exists public.tool_schema_versions add column if not exists runtime_policy jsonb;
alter table if exists public.tool_schema_versions add column if not exists source_fingerprint text;
create table if not exists public.schema_reconciliation_events(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,server_id uuid not null references public.mcp_servers(id) on delete cascade,decision text not null,classification text not null,diff jsonb not null,from_version bigint,to_version bigint,actor_id uuid,created_at timestamptz not null default now());
create table if not exists public.owner_notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,server_id uuid references public.mcp_servers(id) on delete cascade,kind text not null,title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.field_mapping_versions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,server_id uuid references public.mcp_servers(id) on delete cascade,provider text,name text not null,version int not null,mappings jsonb not null,is_template boolean not null default false,created_at timestamptz not null default now(),unique(user_id,name,version));
create table if not exists public.semantic_compression_benchmarks(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,server_id uuid not null references public.mcp_servers(id) on delete cascade,results jsonb not null,created_at timestamptz not null default now());
alter table public.schema_reconciliation_events enable row level security;alter table public.owner_notifications enable row level security;alter table public.field_mapping_versions enable row level security;alter table public.semantic_compression_benchmarks enable row level security;
drop policy if exists "reconciliation owned" on public.schema_reconciliation_events;create policy "reconciliation owned" on public.schema_reconciliation_events for select using(auth.uid()=user_id);
drop policy if exists "notifications owned" on public.owner_notifications;create policy "notifications owned" on public.owner_notifications for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "mapping versions owned" on public.field_mapping_versions;create policy "mapping versions owned" on public.field_mapping_versions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "benchmarks owned" on public.semantic_compression_benchmarks;create policy "benchmarks owned" on public.semantic_compression_benchmarks for select using(auth.uid()=user_id);
