"use client";
import { FormEvent, useState } from "react";
type Setup = { server?: { hosted_endpoint: string }; raw_api_key?: string; raw_task_token?: string; authorize_url?: string; error?: string };
export default function GithubReferencePage() {
  const [userId, setUserId] = useState("demo-user"); const [agentId, setAgentId] = useState("github-issues-agent"); const [result, setResult] = useState<Setup | null>(null); const [loading, setLoading] = useState(false);
  async function setup(event: FormEvent) { event.preventDefault(); setLoading(true); const response = await fetch("/api/reference-integrations/github", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ end_user_id: userId, agent_id: agentId }) }); setResult(await response.json()); setLoading(false); }
  return <main className="mx-auto max-w-4xl space-y-6 p-8"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Five-minute reference</p><h1 className="text-3xl font-bold">GitHub Issues agent</h1><p className="mt-2 text-neutral-600">Creates a repository-locked MCP server, trusted agent key, 15-minute task grant, approval-gated writes, and per-user GitHub consent.</p></div>
    <form onSubmit={setup} className="grid gap-4 rounded border bg-white p-6 md:grid-cols-2"><label className="text-sm">End-user ID<input className="mt-1 w-full rounded border p-2" value={userId} onChange={(e) => setUserId(e.target.value)} /></label><label className="text-sm">Trusted agent ID<input className="mt-1 w-full rounded border p-2" value={agentId} onChange={(e) => setAgentId(e.target.value)} /></label><button disabled={loading} className="rounded bg-neutral-950 px-4 py-2 text-white md:col-span-2">{loading ? "Preparing…" : "Create and connect GitHub"}</button></form>
    {result?.error ? <p className="rounded border border-red-200 bg-red-50 p-4 text-red-800">{result.error}</p> : null}
    {result?.authorize_url ? <section className="space-y-3 rounded border bg-white p-6"><a className="inline-flex rounded bg-blue-600 px-4 py-2 font-semibold text-white" href={result.authorize_url}>Continue to GitHub consent</a><p className="text-sm text-amber-800">Copy both one-time credentials before leaving this page.</p><Secret label="Astrail API key" value={result.raw_api_key} /><Secret label="Task authorization" value={result.raw_task_token} /><Secret label="MCP endpoint" value={result.server?.hosted_endpoint} /><a className="text-sm font-semibold text-blue-700" href="/dashboard/authorization">Inspect lifecycle and task authorization →</a><br/><a className="text-sm font-semibold text-blue-700" href="/dashboard/audit">Inspect intent-linked evidence →</a></section> : null}
  </main>;
}
function Secret({ label, value }: { label: string; value?: string }) { return <div><p className="text-xs font-semibold uppercase text-neutral-500">{label}</p><code className="mt-1 block break-all rounded bg-neutral-100 p-3 text-sm">{value}</code></div>; }
