import { PageFrame } from "@/components/control-plane/PageFrame";
import { getDashboardSessionUser } from "@/lib/dashboard-session";
import { hasServerNeonEnv } from "@/lib/neon/env";
import { createUserDataClient } from "@/lib/neon/server";
export default async function ReliabilityPage(){
 let rows:Array<{provider:string;metric:string;value:number;recorded_at:string}>=[];let warning="";
 if(hasServerNeonEnv()){const user=await getDashboardSessionUser();const result=await createUserDataClient().from("reliability_metrics").select("provider,metric,value,recorded_at").eq("tenant_id",user.id).gte("recorded_at",new Date(Date.now()-86_400_000).toISOString()).order("recorded_at",{ascending:false}).limit(200);rows=(result.data??[]) as typeof rows;warning=result.error?.message??"";}
 const names=["retry","throttle","queue","circuit","provider_error"] as const;const totals=Object.fromEntries(names.map((name)=>[name,rows.filter((r)=>r.metric===name).reduce((sum,r)=>sum+r.value,0)]));
 return <PageFrame eyebrow="Operations" title="Provider reliability" description="Distributed retry, throttle, queue, circuit, and provider-error signals for the last 24 hours.">{warning?<p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{warning}</p>:null}<section className="grid gap-3 md:grid-cols-5">{names.map((name)=><div key={name} className="rounded-xl border border-neutral-200 bg-white p-4"><p className="text-xs uppercase text-neutral-500">{name.replaceAll("_"," ")}</p><p className="mt-2 text-2xl font-semibold">{totals[name]}</p></div>)}</section><section className="rounded-xl border border-neutral-200 bg-white p-5"><h2 className="font-semibold">Recent signals</h2><div className="mt-4 divide-y divide-neutral-100">{rows.slice(0,50).map((row,index)=><div key={`${row.recorded_at}-${index}`} className="grid grid-cols-3 py-2 text-sm"><span>{row.provider}</span><span>{row.metric.replaceAll("_"," ")} · {row.value}</span><span className="text-right text-neutral-500">{new Date(row.recorded_at).toLocaleString()}</span></div>)}{!rows.length?<p className="text-sm text-neutral-500">No reliability events in this window.</p>:null}</div></section></PageFrame>;
}
